###
GET http://localhost:8081/api/v1/user

###
GET http://localhost:8081/api/v1/user/search?firstname=l

###
GET http://localhost:8081/api/v1/user/search?lastname=si

###
GET http://localhost:8081/api/v1/user/search?firstname=pa&lastname=ss

###
GET http://localhost:8081/api/v1/user/1

###
POST http://localhost:8081/api/v1/user/csv
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.csv"
Content-Type: text/csv

<@ ./src/main/resources/test.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST http://localhost:8081/api/v1/user
Content-Type: application/json

{
  "firstName": "Giovanni",
  "lastName": "Rossi",
  "email": "a@b.com",
  "addressLine1": "Via dei Mille, 0",
  "addressLine2": "test",
  "addressPostalCode": "12345",
  "addressCity": "Cosenza",
  "addressState": "Italy"
}

###
PUT http://localhost:8081/api/v1/user/3
Content-Type: application/json

{
  "id": 3,
  "firstName": "Paola",
  "lastName": "Rossi",
  "email": "ciao@ciaone.com",
  "addressLine1": "Via Roma, 100",
  "addressLine2": "",
  "addressPostalCode": "00100",
  "addressCity": "Roma",
  "addressState": "Italia"
}

###
DELETE http://localhost:8081/api/v1/user/2
