###
GET http://localhost:8080/api/v1/user

###
GET http://localhost:8080/api/v1/user/1

###
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "firstName": "a",
  "secondName": "s",
  "email": "d",
  "addressCity": "d",
  "addressLine1": "f",
  "addressLine2": "f",
  "addressPostalCode": "as",
  "addressState": "fh"
}

###
PUT http://localhost:8080/api/v1/user/3
Content-Type: application/json

{
  "id": 3,
  "firstName": "Paola",
  "secondName": "Rossi",
  "email": "ciao@ciaone.com",
  "addressLine1": "Via Roma, 100",
  "addressLine2": "",
  "addressPostalCode": "00100",
  "addressCity": "Roma",
  "addressState": "Italia"
}

###
DELETE http://localhost:8080/api/v1/user/2
