version: "3.7"
services:
  user_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: "mariadb:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: demoapp
      MYSQL_USER: demoapp
      MYSQL_PASSWORD: demoapp
      MYSQL_ROOT_PASSWORD: demoapp
