spring:
  datasource:
    url: ${APP_DB_URI}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  config:
    init:
      db: true
